### PR TITLE
#317: Justification translate to human-readable format

### PR DESCRIPTION
**Pull request by joao-conde**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/317 |
| Dependencies | -- |
| Decisions | Mixin to fetch translations for justification codes to human-readable format. |

image

image

@BeeMargarida  @3rdvision was a bit unsure, maybe this should be moved to:
- commons JS
- or create a new SDK method with core endpoint
- or just leave it as a mixin

### CODE REVIEW

**Review by BeeMargarida — APPROVED** [review]
I'll aprove it, but I don't know if this is the best place (as you mentioned in the PR description). Is this going to be used in other places? This could be moved both to SDK or even Pulse directly, I think it is a bit out of context here without being used in more than 1 place

**Comment by 3rdvision** [comment]
@joao-conde I'm also not sure where this should be but it can be used by ripe-pulse and ripe-util-vue so it sure could be a ripe mixin. As for ripe-commons-js it doesn't seem to have ripe methods so maybe this could be the place

**Comment by joao-conde** [comment]
Used by Pulse by now, but I guess even Robin could use it in the future no? In that case, probably SDK or RIPE Commons. 

Could also just be a new route in https://github.com/ripe-tech/ripe-core/blob/master/src/ripe_core/controllers/api/justification.py though I am not sure what to call it.

What do you think? @BeeMargarida  @3rdvision

**Comment by BeeMargarida** [comment]
> Used by Pulse by now, but I guess even Robin could use it in the future no? In that case, probably SDK or RIPE Commons.
> 
> Could also just be a new route in https://github.com/ripe-tech/ripe-core/blob/master/src/ripe_core/controllers/api/justification.py though I am not sure what to call it.
> 
> What do you think? @BeeMargarida @3rdvision

Robin does not use `this.$ripe` call like that but instead uses context, so as is it would not work...only would work if moved to the SDK

**Comment by joao-conde** [comment]
Closing because a Vue mixin approach will not work for clients not written in Vue, for RIPE Robin for example

**Pull request closed without merging**
