### PR TITLE
#288 button-dropdown disabled prop

### PR DESCRIPTION
**Pull request by joaofsl**
| - | - |
| --- | --- |
| Issue | Issue surged with https://github.com/ripe-tech/ripe-util-vue/issues/288 where the `button-dropdown` needed to be disabled|
| Decisions | Add `disabled` prop to `button-dropdown`|
| Animated GIF ||

### CODE REVIEW

**Review by NFSS10 — APPROVED** [review]
@joaofsl I would probably also do this in the `onDropdownItemClicked` method but looks good!

```javascript
 onDropdownItemClicked(event, item) {
    if (this.disabled) return;
    this.$emit("click:item", event, item);
}
```

**Comment by joaofsl** [comment]
> @joaofsl I would probably also do this in the `onDropdownItemClicked` method but looks good!
> 
> ```js
>  onDropdownItemClicked(event, item) {
>     if (this.disabled) return;
>     this.$emit("click:item", event, item);
> }
> ```

I didn't do it there because technically it could never get there if disabled

**Review by joamag — APPROVED** [review]

**Comment by joamag** [comment]
@joaofsl please check if back-porting is required say to Ripe White, etc.

**Comment by joaofsl** [comment]
@joamag this component only exists here

**Pull request merged**
