### PR TITLE
Generic Form component - second try

### PR DESCRIPTION
**Pull request by joamag**
| - | - |
| --- | --- |
| Issue |The original PR (conversation) here https://github.com/ripe-tech/ripe-components-vue/pull/374 |
| Dependencies | -- |
| Decisions | `form-ripe` component |
| Animated GIF | generic-form_fixes |

### CODE REVIEW

**Comment by gcandal** [comment]
@NFSS10 please close the missing gaps (https://github.com/ripe-tech/ripe-components-vue/pull/374#issuecomment-696186336) so that this component can be used in https://github.com/ripe-tech/ripe-white-admin-ui/blob/master/vue/components/context/context-edit/context-edit.vue

**Comment by joamag** [comment]
@gcandal this is a fast track as it's blocking some developments

**Comment by gcandal** [comment]
@NFSS10 let's change the way you can specify types. Instead of just `type` let's use:
- `type`: `boolean`, `file`, `image`, `text`, ...
- `meta` (optional): used to refine a given type. For instance, you might want to have `url` for `text` that would have some kind of special behavior. For instance, `text` and `long` might lead to a `textarea`, while `image` might have `url` (like ripe-white-admin-ui where you just write a URL) or `blob` (which means an image-uploader)

**Comment by gcandal** [comment]
@NFSS10 please add semantic classes that can be used for testing

**Review by gcandal — APPROVED** [review]

**Comment by joamag** [comment]
@gcandal @NFSS10 let's first finish the development and then validate the PR

**Review by gcandal — APPROVED** [review]

**Comment by joamag** [comment]
@gcandal I believe the select and tabs changes must be back-ported to the ripe-commons/ripe-white environment

**Pull request merged**
