### PR TITLE
#576 Animations for 404 and 500 error codes

### PR DESCRIPTION
**Pull request by NFSS10**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-white/issues/576 |
| Dependencies | -- |
| Decisions | Showing animation for 404 and 500 status codes |
| Animated GIF | error_template_with_animations_improved |

### CODE REVIEW

**Comment by gcandal** [comment]
@NFSS10 can you please expose the problem to @hugo-gomes so he can ask Jorge to generate a "trimmed" SVGA if possible?

**Comment by NFSS10** [comment]
> @NFSS10 can you please expose the problem to @hugo-gomes so he can ask Jorge to generate a "trimmed" SVGA if possible?

I asked if 404 can be adjusted :+1:

**Comment by jorgefernandess** [comment]
@NFSS10 this is the first cropped version, the problem is that it hides the elements outside the bounding box.
[cropped-error-animations.zip](https://github.com/ripe-tech/ripe-components-vue/files/5246746/cropped-error-animations.zip)

**Review by hugo-gomes — CHANGES_REQUESTED** [review]
rename `500-loop-cropped.svg` to `500-error-animation.svg` and `404-loop-cropped.svg` to `404-error-animation.svg`

**Review by hugo-gomes — APPROVED** [review]

**Review by joamag — APPROVED** [review]

**Review by joamag — APPROVED** [review]

**Pull request merged**
