### PR TITLE
#56 Persistent filter

### PR DESCRIPTION
**Pull request by NFSS10**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-pulse/issues/56 |
| Decisions | • Added a select that when pressed opens a dropdown with various filters. The user then can choose a filter. The user can also edit, delete and create new filters. <br>• Depends on the addition of slots in "checkbox" component implemented in PR: https://github.com/ripe-tech/ripe-components-vue/pull/192 |
| Animated GIF | persistent_filters_1<br>**Save new filter modal:**<br>persitent-filters_imp2 <br>**Creating a filter that already exists, updates the existing one:** persistent-filters_imp3<br>**Updates filter based on url:**<br>persistent_filters_url |

### CODE REVIEW

**Comment by NFSS10** [comment]
@gcandal uses changes of the pending PRs: https://github.com/ripe-tech/ripe-components-vue/pull/163 and https://github.com/ripe-tech/ripe-components-vue/pull/164 .

**Comment by gcandal** [comment]
@NFSS10 please address the TODOs (search the code), there's some stuff missing that's important, please drive that boat forward.

**Comment by gcandal** [comment]
@NFSS10 next round of improvements:
- Checking brand, factory or channel triggers the appearance of a dropdown populated with getBrands / getFactories / getChannels (hard-coded for now)
- If a dropdown would only have 1 option then don't show it
- If a dropdown has 0 options then don't even show the checkbox
- If all dropdowns are empty then don't show the "Tenancy" section

**Comment by gcandal** [comment]
@NFSS10 yet more improvements:
- Create filter with duplicated name = update existing filter
- `tenacy` -> `tenancy`
- When I select a filter it currently turns black immediately. This is weird because it turns black and then the dropdown closes immediately. Think of a simple approach to fix this. An alternative might be only showing black when the dropdown is opening, but it might get weird as well. The other could involve listening to `onanimationend`. This is exploratory at this point, I'm not sure what the solution could be.

**Comment by gcandal** [comment]
@BeeMargarida please fix the conflicts

**Comment by gcandal** [comment]
Splitting this into multiple PRs:
https://github.com/ripe-tech/ripe-components-vue/pull/222
https://github.com/ripe-tech/ripe-components-vue/pull/223
https://github.com/ripe-tech/ripe-components-vue/pull/224
https://github.com/ripe-tech/ripe-components-vue/pull/225
https://github.com/ripe-tech/ripe-components-vue/pull/226

**Comment by joamag** [comment]
@gcandal we still need to rebae this

**Comment by gcandal** [comment]
@BeeMargarida or @NFSS10 can one of you please fix the conflicts?

**Comment by joamag** [comment]
This one was tough :(

**Pull request closed without merging**
