### PR TITLE
#316 Calendar re-design v1

### PR DESCRIPTION
**Pull request by 3rdvision**
| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-design/issues/316#issuecomment-851534607 <br> proposed solution 1 |
| Decisions | - Add calendar re-design v1. |
| Dependencies | https://github.com/ripe-tech/ripe-components-vue/pull/505 |
| Animated GIF | Below |

https://user-images.githubusercontent.com/24736423/127488160-36e39145-7c61-4d45-b234-4b97d83f319d.mov

### CODE REVIEW

**Comment by gcandal** [comment]
Shouldn't the animation time for the fade in the header should be the same as for the content?

**Comment by gcandal** [comment]
Waiting on https://github.com/ripe-tech/ripe-components-vue/pull/505

**Comment by gcandal** [comment]
@3rdvision conflicts

**Comment by gcandal** [comment]
@3rdvision the animations need some small tunes:
- Same timing for all fades
- Make them faster :)

**Comment by 3rdvision** [comment]
> @3rdvision the animations need some small tunes:
> 
>     * Same timing for all fades
> 
>     * Make them faster :)

I refactored the way animations were being displayed. Using `transition` created a bad experience because creating to HTML was not smooth enough as using v-show and `transition-group`.
I added expand and collapse animations.

They aren't faster in transition time but they are smoother. Let me know what you think and if you still want them faster. Currently it's using 0.35s

**Comment by gcandal** [comment]
Remove hover on header when header=False

**Review by gcandal — APPROVED** [review]

**Review by joamag — APPROVED** [review]

**Pull request merged**
