### PR TITLE
feat: add `pagination` component

### PR DESCRIPTION
**Pull request by beneditomauro**
| - | - |
| --- | --- |
| Issue | [ripe-util-vue/#307](https://github.com/ripe-tech/ripe-util-vue/issues/307) |
| Decisions | Migrate `pagination` component from [ripe-white](https://github.com/ripe-tech/ripe-white/tree/master/vue/components/molecules/pagination) |
| Animated GIF | nVWubtB2jy|

### CODE REVIEW

**Review by NFSS10 — CHANGES_REQUESTED** [review]

**Review by NFSS10 — APPROVED** [review]

**Review by 3rdvision — COMMENTED** [review]
All good, maybe just a small fix in the size of the page active so it's dynamic enough to include the number without overflow (see image below)

image

**Comment by beneditomauro** [comment]
> All good, maybe just a small fix in the size of the page active so it's dynamic enough to include the number without overflow (see image below)
> 
cV0uCMjI9Y

**Comment by beneditomauro** [comment]
> All good, maybe just a small fix in the size of the page active so it's dynamic enough to include the number without overflow (see image below)
> 
> image

✅
cV0uCMjI9Y

**Review by 3rdvision — APPROVED** [review]

**Comment by beneditomauro** [comment]
@3rdvision this is a backport and it's not a risky PR, I think we could assign conde for the merge

**Review by joao-conde — APPROVED** [review]

**Pull request merged**
